### ISSUE TITLE
Cannot reslove domain [ .id ]

### ISSUE THREAD

**Issue by 3xploiton3** [RobBiddle/Get-WHOIS#2]
https://github.com/PowerShell/PowerShellGallery/issues/283

**Comment by RobBiddle** [comment]
I'm currently using the whois-servers.net DNS service to identify WHOIS servers.
They don't have an entry for the .id TLD.

I have a fix; I'm going to be using the IANA WHOIS service when the DNS lookup fails.
Hopefully that will cover all of the TLDs.
